### ISSUE TITLE
Package does not install with pip

### ISSUE THREAD

**Issue by veleritas** [dhimmel/hetio#2]
The hetio package fails to properly install when using the command `pip install git+https://github.com/dhimmel/hetio.git#egg=hetio` as specified in the README.

From a virtual environment with pip 8.1.2 and setuptools 28.0.0 only, running `pip install git+https://github.com/dhimmel/hetio.git#egg=hetio` gives the following error:

```
Collecting hetio from git+https://github.com/dhimmel/hetio.git#egg=hetio
  Cloning https://github.com/dhimmel/hetio.git to /tmp/pip-build-7e3bcckm/hetio
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-7e3bcckm/hetio/setup.py", line 2, in <module>
        import pypandoc
    ImportError: No module named 'pypandoc'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-7e3bcckm/hetio/
```

This seems to go away if you run `pip install pypandoc` first prior to installing, since it gets stuck at a different step (lack of the pandoc package).

**Comment by dhimmel** [comment]
I posted the hetio package to PyPI recently (https://pypi.python.org/pypi/hetio). However, I'm actually getting the following error on my Mac when I run `pip install hetio`:

```
Collecting hetio
  Could not find a version that satisfies the requirement hetio (from versions: )
No matching distribution found for hetio
```

Also good catch that the README is confusing. I should point users to PyPI install rather than GitHub install. See if `pip install hetio` works for you.

I'll keep looking into this.

**Comment by veleritas** [comment]
Installing from PyPI didn't work for me either. It was the first thing that I tried, but I also got the same error as you. That was why I tried to install from github. The real issue is that this seems to be blocking for setting up the Anaconda environment for the [`integrate`](https://github.com/dhimmel/integrate) repo, which I'm not sure how to overcome at the moment.

**Comment by dhimmel** [comment]
BTW the error `ImportError: No module named 'pypandoc'` is because you don't have [`pypandoc`](https://pypi.python.org/pypi/pypandoc) installed, which is [used by `setup.py`](https://github.com/dhimmel/hetio/blob/ace55ab34cf1359fb8bc234fcd492156eb0edebb/setup.py#L6). But yeah that's an annoying dependency that I'll consider removing.

> The real issue is that this seems to be blocking for setting up the Anaconda environment for the integrate repo, which I'm not sure how to overcome at the moment.

The solution path will be me fixing the hetio install issue and then changing the integrate `environment.yml` to use the pip hetio. Will aim to fix by midday tomorrow.

**Comment by dhimmel** [comment]
Okay I've fixed the "No matching distribution" issue. I had forgotten to run the last _upload_ step for [putting a package on PyPI](http://peterdowns.com/posts/first-time-with-pypi.html). However, there's still the `pypandoc` dependency issue.

**Comment by dhimmel** [comment]
321fc7471c37129d5764baafc10d2c6dce5a832b removed the `pypandoc` installation issue. Both methods of pip installation should now work. Close if you agree 😸 .

**Comment by veleritas** [comment]
Thanks, that solved the issues.

**Comment by nateshmbhat** [comment]
Try `pip install --upgrade setuptools`
