### ISSUE TITLE
Py2neo 3 compatibility

### ISSUE THREAD

**Issue by veleritas** [dhimmel/hetio#4]
I'm working on upgrading `hetio` to be compatible with `py2neo` 3. Since many parts of the `rephetio` pipeline use `hetio`, what do you think the easiest way would be to test them all?

So far I've managed to get `hetio` to load nodes into Neo4j 3.1.1.

**Comment by dhimmel** [comment]
It's ideal if we can upgrade to py2neo 3 and then make a new hetio release. Therefore, you can choose your hetio release based on whether you want to use py2neo 2 or 3.

**Comment by veleritas** [comment]
I've forked `hetio` to my account, will install as recommended by cloning and doing a `pip install -e .`

After it seems that the new `hetio` plays nice with the pipeline, then I will make a pull request.

**Comment by veleritas** [comment]
If I want to add additional features to `hetio` such as having a progress bar (via `tqdm`) for the node and edge import steps, how would I specify that `tqdm` is a dependency of `hetio`?

**Comment by dhimmel** [comment]
> how would I specify that tqdm is a dependency of hetio?

You can add an `install_requires` in `setup.py`. See [example here](https://github.com/pypa/sampleproject/blob/cec59671175bc2c86563ac80c90ba28b068a1335/setup.py#L78-L82).

Currently, I didn't put pandas or py2neo as dependencies although arguable they should be. Or we could put these packages in [`extras_require`](http://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies).

One option for the progress bar is that you can try to import tqdm. If it fails continue without if that's not too hard to implement. Otherwise, you can just make the progress bar always on.

**Comment by veleritas** [comment]
I've made some small modifications to `hetio` and opened up a pull request!
